### ISSUE TITLE
Add speakers

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap-day#6]
- [x] Eric Alli
- [x] Alex Blom
- [x] Micheal Brooks
- [x] [Raymond Camden](http://raymondcamden.com/about-me)
- [x] David Frahm
- [x] Ryan Hanna
- [x] Mike Hartington
- [x] Shawn Jansepar
- [x] Anis Kadri
- [x] Bruce Lefebvre
- [x] Simon Macdonald
- [x] Loki Meyburg
- [x] Martin Poschenrieder
- [x] Ryan J Salva
- [x] Holly Schinsky
- [x] Dean Haddock
- [x] Brian Rinaldi
- [x] TJ VanToll
- [x] Renée Lance
- [x] Masahiro Tanaka
- [x] Shazron Abdullah
- [x] Garth Braithwaite
- [x] Don Coleman
- [x] Jesse MacFadyen
- [x] Tim Kim

**Comment by jenlgray** [comment]
1. Ryan Hanna 
   Ryan Hanna is the Director of Engineering at Sworkit. He began learning to code online in 2012 and grew his side project into a top Health and Fitness app with over 10 million downloads. He is also a co-organizer of codebar.io in Brighton, England | @heryandotus

![ryan-bio-photo](https://cloud.githubusercontent.com/assets/9487317/10925542/58b933b4-824c-11e5-8818-409345f2be72.JPG)
1. David Frahm
   Mobile and frontend developer focused on Ionic SDK and AngularJS apps, with a strong background in UX, Agile, eXtreme Programming, and startup growth.  Living in the Midwest and contributing to the world.

![davidfrahm-square-512](https://cloud.githubusercontent.com/assets/9487317/10925566/7da02390-824c-11e5-8e8c-5c633ca93b1d.jpg)
1. Shawn Jansepar
   Shawn is an Engineering Manager on the Product and Customer Success Teams at Mobify. He loves to hack both on the front-end and back-end, with a heavy focus on the user experience. When he isn't hacking, you likely find him playing hockey/video games, eating, or travelling. Shawn has a BSc in Computer Science from Simon Fraser University in Vancouver. You can follow him on Twitter at @shawnjan8.

https://www.dropbox.com/s/p3p7lgorwfemibu/profile.png?dl=0
1. Loki Meyburg
   Loki is the product guy at Mobify working on apps. He is also the creator of Stacker, an open source project to kickstart the development of iOS apps. Previously he was the first employee at Medeo, a medical startup, that was acquired in 2014. Graduated with Honours in Business and Computer Science from the University of British Columbia. You can follow him on Twitter at @lokimeyburg

http://cloud.loki.io/image/2Q411a2b2g1g
1. Eric Alli
   Eric Alli is a San Francico based designer & engineer who enjoys building useful products for niche spaces and sharing his affinity for music and art.

![eric_alli](https://cloud.githubusercontent.com/assets/9487317/10925680/7ba3a99e-824d-11e5-9325-915e260d7975.jpeg)
1. Michael Brooks (from past PGD EU site)
2. Martin Poschenrieder
   Martin Poschenrieder has been working in the mobile industry for most of the past decade. He began his career as an intern for one of the few German handset manufacturers, years before Android and iPhone were launched. After involvement with several app projects, he soon realized that one of the biggest pain-points in development was mobile app testing. In order to ease this pain, he started Testmunk. Testmunk is based in Silicon Valley, and provides automated app testing over the cloud.

![martin_poschenrieder](https://cloud.githubusercontent.com/assets/9487317/10925742/06266dfe-824e-11e5-8e07-bfbe2c40c77a.jpeg)
1. Ryan J Salva
   JavaScript developer, Apache Cordova committer, Visual Studio program manager, CrossFitter, sci-fi connoisseur and whiskey enthusiast. With over 15 years of experience in software development, it’s hard to find a corner of the web where he hasn’t worked, but the important thing to know is this: Ryan is a passionate storyteller with deep insight into market forces, technology, user experience and design. Today, he owns tooling for cross-platform mobile app development at Microsoft. Tomorrow, the world.

![ryanjsalva](https://cloud.githubusercontent.com/assets/9487317/10925757/3d398272-824e-11e5-9f37-610033089a3f.jpg)

**Comment by jenlgray** [comment]
Alex Blom - Alex Blom is a hacker who works with Ember, Ruby & Go. He is a Partner at Isle of Code, a Toronto based agency focused on Ember, and using Ember in PhoneGap & iBeacon contexts. Prior, Alex was building a browser extension based startup in Ember (morse). 

![alex](https://cloud.githubusercontent.com/assets/9487317/11026941/a201ad38-866d-11e5-945a-93ea5a166bb4.jpg)

**Comment by jenlgray** [comment]
Dean Haddock - Dean Haddock is the Managing Director of Digital & Technical Innovation for StoryCorps, the national oral history project--one of the largest collections of human voices ever assembled--and popular NPR/PBS broadcast. He and his team design and build apps, websites and other platforms to further StoryCorps' mission of recording and preserving the stories of everyday people across the US and around the world. Most recently Dean led StoryCorps' 2015 $1m TED Prize initiative to build a mobile app and platform that anyone can use to record and archive oral history interviews permanently at the Library of Congress. He is a Nieman Foundation Visiting Fellow, a Knight Foundation Prototype Fund awardee, a two-time Google Fellow to the Personal Democracy Forum and a civic hacktivist.

![haddock-3](https://cloud.githubusercontent.com/assets/9487317/11077843/4c01755a-87bf-11e5-91c9-07042c0052fd.jpg)

**Comment by jenlgray** [comment]
Brian Rinaldi - Brian Rinaldi is the Developer Content Manager at Telerik where he helps the Developer Relations team create top notch content for the developer community on the Telerik Developer Network. He is also co-editor of Mobile Web Weekly. You can follow Brian via @remotesynth on Twitter.

![brian rinaldi headshot](https://cloud.githubusercontent.com/assets/9487317/11102784/d7f0496c-887b-11e5-99c9-f5f215a7ce4d.jpg)

**Comment by jenlgray** [comment]
TJ VanToll - TJ VanToll is a front-end developer, author, and a senior developer advocate for Telerik. TJ has over a decade of web development experience, including a few years working on the jQuery team. Nowadays, he spends his time helping web developers build mobile apps through projects like Cordova and NativeScript. TJ is @tjvantoll on Twitter and tjvantoll on GitHub.

![tj headshot](https://cloud.githubusercontent.com/assets/9487317/11122428/70ae2894-8918-11e5-8abc-4862e5829b55.jpg)

**Comment by GarthDB** [comment]
@jenlgray I'll add them today.

—

**Comment by jenlgray** [comment]
1. Renée Lance - Adobe Solutions Consultant, ANZ

Renée is a seasoned Web and UX designer and now an Adobe Solutions Consultant evangelizes Creative Cloud, Document Cloud and digital innovation. With more than 10 years experience with digital design, Renée is a passionate professional who is dedicated in developing solutions for business and creative professionals ensuring they remain competitive and deliver engaging customer experiences. Her creative-thinking skills and technical experience assist customers deliver innovative outcomes for creative and non-traditional creative industries. Twitter: @AdobeGeekGirl Linkedin: https://au.linkedin.com/in/reneelance

![reneelance](https://cloud.githubusercontent.com/assets/9487317/11309252/fe0a3256-8f7f-11e5-8015-416d7cc18add.png)
1. Masahiro Tanaka - CEO of Asial Corporation 

Masa is the CEO of Asial Corporation, the company behind Japan's #1 hybrid app development tools, Monaca and Onsen UI. He started his company as a pioneer in web and mobile communities in Japan, writing numerous PHP books and initiating Cordova meetups. Masa still
 maintains a leadership role within mobile and IoT communities in Japan and overseas as a hybrid app development vanguard and framework trendsetter.

![massie bio](https://cloud.githubusercontent.com/assets/9487317/11309542/b1ae1830-8f81-11e5-8d8c-dead769a4a3b.jpeg)
1. Shazron Abdullah - Web Developer, Adobe

Based in San Francisco, by way of Vancouver, Canada and Singapore, Shaz has nearly two decades of software development experience getting with the nitty gritty of Windows, OS X and iOS and probably helped code something you know. Currently he helps maintain the iOS platform of Apache Cordova and Adobe PhoneGap and has been part of the project for quite some time. 

![slack-imgs](https://cloud.githubusercontent.com/assets/9487317/11309601/fd48f0d0-8f81-11e5-889f-2fe5d3155b2a.jpg)
1. Garth Braithwaite (your details here)
2. Don Coleman, Director, Chariot Solutions

Don enjoys hacking with phones, Arduino and other hardware. He has written PhoneGap plugins for Bluetooth and NFC. Don is the co-author of "Make:Bluetooth" and "Beginning NFC".

![doncoleman](https://cloud.githubusercontent.com/assets/9487317/11309769/f7e6f370-8f82-11e5-87d9-fe60d8742236.jpg)
1. Jesse MacFadyen - Sr. Computer Scientist, Adobe

A self-proclaimed prolific hacker, Jesse often loses interest before he has a chance to fi

![jesse-macfadyen_big_360](https://cloud.githubusercontent.com/assets/9487317/11310475/2baee448-8f87-11e5-9de6-ef407065d010.jpg)

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/11314172/6dab622c-8fa0-11e5-9612-4a6bba1bf3e8.png)

**Comment by jenlgray** [comment]
Updated Jesse bio/headshot:
1. Jesse MacFadyen - Sr. Computer Scientist, Adobe

Jesse is a primordial PhoneGap contributor that has been around long enough to see many phonegap-killers come and go. He has written plugins for everything from the device accelerometer to bluetooth connected wearables like the ms-band, across windows, windows phone, android and ios. A self-proclaimed prolific procrastinator, Jesse often loses interest before he has a chance to fi

Use photo in previous comment

**Comment by jenlgray** [comment]
1. Tim Kim - Expert Keyboard Masher, Adobe

Hacking on software by day and drawing digital illustrations by night,  Tim enjoys all forms of creativity possible in the digital realm. Currently he works on the PhoneGap Developer App and making stickers for the PhoneGap team. When Tim isn't hard at work, you can can find him trying to memorize movie quotes, playing video games or generally ignoring his ever growing to-do list. 

![unknown](https://cloud.githubusercontent.com/assets/9487317/11596548/dd654646-9a72-11e5-8eeb-05f26811c0e4.jpeg)
